import {readDocument} from './document-reader.js';
import {buildArticleDocx,sourceFootnotes} from './docx-engine.js';
import {analyzeThesis,generatePlan,diagnostics,syncReferences} from './article-ai.js';
import {LocalAI,MODEL_PROFILES,mapWithAI,synthesizePlan,translateWithAI,chatWithDocument} from './local-ai.js';
import {esc,norm,wc,ROLES,itemText,sourceIds,recalc,safeFilename,checkAbort,VERSION} from './utils.js';
const $=selector=>document.querySelector(selector);
const icons={spark:'M12 3l2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4L12 3z',file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zm0 0v6h6M8 13h8M8 17h6',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',map:'M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3zm6-3v15m6-12v15',check:'M9 12l2 2 4-4M12 3l8 4v5c0 5-8 9-8 9s-8-4-8-9V7z',chat:'M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8z',upload:'M12 16V3m-5 5l5-5 5 5M4 15v5a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-5',download:'M12 3v13m-5-5l5 5 5-5M4 17v4h16v-4',arrow:'M5 12h14m-5-5l5 5-5 5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10l2 2M5 19l2-2M17 7l2-2',help:'M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4m0 4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',edit:'M16 3l5 5-12 12-6 1 1-6zM14 5l5 5',close:'M6 6l12 12M6 18L18 6',lock:'M7 11V7a5 5 0 0 1 10 0v4M5 11h14v10H5z',book:'M4 3h6l2 2 2-2h6v16h-6l-2 2-2-2H4zM12 5v16',cpu:'M7 7h10v10H7zM3 8h4m-4 8h4m10-8h4m-4 8h4M8 3v4m8-4v4m-8 10v4m8-4v4',refresh:'M20 7v5h-5M4 17v-5h5M6 7a7 7 0 0 1 11-2l3 7M4 12l3 7a7 7 0 0 0 11-2',copy:'M9 9h12v12H9zM15 9V3H3v12h6'};
function icon(name,cls=''){return `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.file}"/></svg>`;}
const ai=new LocalAI();
const state={file:null,doc:null,analysis:null,plan:null,english:null,mapping:{},busy:false,controller:null,revision:0,tab:'article',editing:false,chat:[],stage:'idle'};
$('#app').innerHTML=`
<div class="app-shell">
 <aside class="sidebar">
  <a href="./" class="brand"><span class="brand-mark">Z<span>•</span></span><span>ZAIN.NET<small>Article Studio</small></span></a>
  <div class="nav-caption">WORKSPACE</div>
  <nav aria-label="Navigasi utama">
   <button class="nav-item active" data-go="article">${icon('grid')}<span>Studio artikel</span><span class="nav-dot"></span></button>
   <button class="nav-item" data-go="map">${icon('map')}<span>Peta sumber</span></button>
   <button class="nav-item" data-go="quality">${icon('check')}<span>Pemeriksaan</span><span class="count-badge" id="issueCount">0</span></button>
   <button class="nav-item" data-go="chat">${icon('chat')}<span>Tanya dokumen</span></button>
  </nav>
  <div class="nav-caption second">PREFERENSI</div>
  <button class="nav-item" id="openAI">${icon('cpu')}<span>Mesin AI lokal</span><span class="new-badge">LLM</span></button>
  <button class="nav-item" id="helpNav">${icon('help')}<span>Panduan singkat</span></button>
  <div class="sidebar-bottom"><div class="privacy-mark">${icon('lock')}<span>Pemrosesan lokal<small>Berkas tetap di perangkat Anda.</small></span></div><div class="sidebar-version">ZAIN.NET STUDIO <span>V${VERSION}</span></div></div>
 </aside>
 <main class="main">
  <header class="topbar"><div class="breadcrumb">Workspace <span>/</span> <strong>Studio artikel</strong></div><div class="top-actions"><button class="engine-pill" id="aiBadge"><span class="status-dot"></span><span id="aiLabel">AI belum aktif</span></button><div class="avatar">ZN</div></div></header>
  <div class="content">
   <section class="hero"><div class="hero-copy"><div class="eyebrow"><span></span> SKRIPSI → ARTIKEL ILMIAH</div><h1>Penelitian Anda.<br><em>Artikel yang lebih rapi.</em></h1><p>Susun draft, telusuri sumber, dan rapikan format.<br>Dibantu AI lokal, dengan hasil yang bisa Anda periksa.</p><div class="hero-tags"><span>${icon('lock')} Tanpa API token</span><span>${icon('book')} DOCX · PDF · OCR</span></div></div>
    <div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="mini-paper back-paper"><div class="paper-rule"></div><div class="paper-rule short"></div></div><div class="mini-paper front-paper"><div class="paper-mini-tag">RESEARCH ARTICLE</div><div class="mini-title">Satu penelitian.<br>Banyak gagasan.</div><div class="paper-rule"></div><div class="paper-rule"></div><div class="paper-rule short"></div><div class="mini-chart"><i></i><i></i><i></i><i></i><i></i></div><div class="paper-rule"></div></div><div class="floating-label">${icon('spark')} Article Studio <span>2.1</span></div></div>
   </section>
   <div class="stats"><div class="stat">${icon('file')}<div><span>Kata sumber</span><b id="sourceWords">—</b></div></div><div class="stat">${icon('edit')}<div><span>Kata artikel</span><b id="articleWords">—</b></div></div><div class="stat">${icon('map')}<div><span>Bagian terpetakan</span><b id="structureStat">0<span>/ 4</span></b></div></div><div class="stat">${icon('book')}<div><span>Referensi artikel</span><b id="referenceStat">—</b></div></div></div>
   <div class="workspace">
    <aside class="setup card"><div class="card-title"><span class="step-number">01</span><div><h2>Siapkan skripsi</h2><p>Sumber yang utuh, hasil lebih baik.</p></div></div>
     <div class="setup-body">
      <label class="dropzone" id="dropzone"><input id="file" type="file" accept=".docx,.pdf,.txt,.png,.jpg,.jpeg"><span class="upload-circle">${icon('upload')}</span><strong id="fileName">Pilih berkas skripsi</strong><span id="fileDetail">Seret berkas, atau klik untuk memilih</span><small>DOCX, PDF, TXT, PNG/JPG · maks. 100 MB</small></label>
      <div class="field"><label for="outputMode">Cara menyusun artikel</label><select id="outputMode"><option value="ai">AI lokal · susun ulang & ringkas</option><option value="source">Draft dari teks sumber</option></select><small id="outputHint">Aktifkan model lewat tombol Siapkan AI.</small></div>
      <div class="field"><label for="mode">Panjang draft</label><select id="mode"><option value="contoh">Seimbang · sekitar 3.400 kata</option><option value="ringkas">Ringkas · sekitar 2.300 kata</option><option value="lengkap">Lengkap · sekitar 5.200 kata</option></select><small>Panjang aktual mengikuti sumber, tabel, dan hasil ringkasan.</small></div>
      <div class="field"><label for="instructions">Arahan tambahan <span>opsional</span></label><textarea id="instructions" rows="3" maxlength="500" placeholder="Contoh: Fokus pada hasil penelitian. Gunakan bahasa akademik yang mudah dipahami."></textarea><small id="instructionsHint">Arahan isi digunakan pada mode AI lokal.</small></div>
      <div class="check-stack"><label><input id="ocr" type="checkbox" checked><span>Baca halaman scan dengan OCR</span></label><label><input id="includeTables" type="checkbox" checked><span>Sertakan tabel sumber</span></label><label><input id="includeEnglish" type="checkbox"><span>Terjemahkan abstrak ke Inggris</span></label></div>
      <details class="settings-details"><summary>Data & format artikel ${icon('settings')}</summary><div class="details-content"><div class="field"><label for="title">Judul artikel</label><textarea id="title" rows="3" placeholder="Deteksi dari sumber"></textarea></div><div class="field"><label for="author">Nama penulis</label><input id="author" placeholder="Deteksi dari sumber"></div><div class="field"><label for="prodi">Program studi</label><input id="prodi" placeholder="Program studi"></div><div class="field"><label for="univ">Universitas</label><input id="univ" placeholder="Universitas"></div><div class="two-fields"><div class="field"><label for="fontSize">Ukuran huruf</label><select id="fontSize"><option>12</option><option>11</option><option>10</option></select></div><div class="field"><label for="lineSpacing">Spasi isi</label><select id="lineSpacing"><option value="1.5">1,5</option><option value="1">1</option><option value="2">2</option></select></div></div><small>Word: A4 · margin 3 cm · Times New Roman. Abstrak spasi 1; referensi dengan inden menggantung.</small></div></details>
      <button id="run" class="button primary full" disabled>${icon('spark')}<span>Susun artikel</span>${icon('arrow')}</button>
      <button id="configureAI" class="button secondary full">${icon('cpu')} Siapkan AI lokal</button>
      <label class="auto-check"><input id="autoDownload" type="checkbox" checked> Unduh otomatis setelah selesai</label>
      <div id="progressWrap" class="progress-wrap hidden"><div class="progress-track"><i id="progressBar"></i></div><div class="progress-caption"><span id="progressLabel">Menyiapkan…</span><button id="cancel" type="button">Batalkan</button></div></div>
      <div id="status" class="inline-status" role="status" aria-live="polite">Unggah skripsi untuk mulai.</div>
     </div>
    </aside>
    <section class="result card"><div class="result-head"><div class="card-title"><span class="step-number">02</span><div><h2>Ruang penyuntingan</h2><p id="resultSubtitle">Dari sumber hingga draft yang siap diperiksa.</p></div></div><span class="draft-badge" id="draftBadge">BELUM ADA DRAFT</span></div>
      <div class="tabs" role="tablist"><button class="tab active" data-tab="article" role="tab">Artikel</button><button class="tab" data-tab="map" role="tab">Peta sumber</button><button class="tab" data-tab="quality" role="tab">Pemeriksaan</button><button class="tab" data-tab="chat" role="tab">Tanya dokumen</button></div>
      <div id="pane-article" class="pane active"><div id="articleToolbar" class="article-toolbar hidden"><span id="draftInfo"></span><button id="editToggle" class="text-button">${icon('edit')} Sunting isi</button></div><div id="articleArea" class="article-area"></div></div>
      <div id="pane-map" class="pane"><div class="pane-intro"><h3>Kenali sumber setiap bagian.</h3><p>Pemetaan mengikuti judul dan isi, bukan nomor BAB. Pilih beberapa blok jika satu bagian tersebar.</p></div><div id="mapArea"></div><button class="button secondary" id="applyMapping" disabled>${icon('refresh')} Terapkan peta & susun ulang</button></div>
      <div id="pane-quality" class="pane"><div class="pane-intro"><h3>Periksa sebelum digunakan.</h3><p>Validasi otomatis membantu menemukan masalah. Makna, sitasi, dan format jurnal tetap perlu review.</p></div><div id="qualityArea"></div><div class="field reference-field"><label for="referencePolicy">Kebijakan daftar pustaka</label><select id="referencePolicy"><option value="cited">Referensi yang cocok dengan sitasi</option><option value="all">Semua referensi dari sumber</option></select><small>AI tidak membuat referensi baru. Footnote tetap disertakan meski pasangan referensinya belum ditemukan.</small></div></div>
      <div id="pane-chat" class="pane"><div class="pane-intro"><h3>Diskusikan penelitian Anda.</h3><p>Ajukan pertanyaan tentang skripsi. AI mencari potongan sumber yang relevan dan menyertakan penandanya.</p></div><div class="chat-suggestions"><button data-question="Apa tujuan penelitian ini?">Tujuan penelitian</button><button data-question="Apa metode penelitian dan jumlah sampelnya?">Metode & sampel</button><button data-question="Apa temuan utama penelitian ini?">Temuan utama</button></div><div id="chatLog" class="chat-log" aria-live="polite"></div><form id="chatForm" class="chat-form"><input id="chatInput" placeholder="Tanyakan sesuatu tentang sumber…" maxlength="500" aria-label="Pertanyaan tentang skripsi"><button id="chatSend" class="button primary" aria-label="Kirim pertanyaan">${icon('arrow')}</button></form><small class="chat-note">Jawaban AI perlu dibandingkan dengan sumber. Chat tidak mengubah artikel.</small></div>
      <div class="export-bar"><div class="export-hint">${icon('check')}<span>Review dulu, lalu simpan.<small>Hasil akhir berupa Word yang bisa disunting.</small></span></div><div class="export-actions"><button id="report" class="button secondary" disabled aria-label="Unduh laporan pemeriksaan">${icon('file')} Laporan</button><button id="download" class="button primary" disabled>${icon('download')} Unduh DOCX</button></div></div>
    </section>
   </div>
   <footer class="footer"><span>Dibuat untuk pekerjaan akademik yang lebih tertata.</span><span>ZAIN.NET · Article Studio V${VERSION}</span></footer>
  </div>
 </main>
</div>
<dialog id="aiDialog" class="dialog ai-dialog"><div class="dialog-head"><div><span class="eyebrow small">AI DI PERANGKAT ANDA</span><h2>Siapkan mesin AI lokal</h2></div><button class="icon-button" id="closeAI" aria-label="Tutup">${icon('close')}</button></div><p class="dialog-lead">Model bahasa membantu memetakan sumber, merangkum artikel, menerjemahkan abstrak, dan menjawab pertanyaan. Tidak perlu API token.</p><div class="engine-tabs"><button class="active" data-engine="browser">${icon('cpu')} Di browser</button><button data-engine="ollama">${icon('settings')} Ollama laptop</button></div><div id="browserConfig"><div class="field"><label for="browserModel">Pilih model</label><select id="browserModel">${MODEL_PROFILES.map(m=>`<option value="${m.id}" ${m.id.includes('4B-')?'selected':''}>${m.label} · ${m.memory}</option>`).join('')}</select></div><div class="model-note"><b>Unduhan satu kali, pemrosesan tetap lokal.</b><p>Bobot model tidak disertakan dalam ZIP. Unduhan awal berukuran besar dan membutuhkan internet. Pilih model sesuai memori GPU. WebGPU membutuhkan Chrome/Edge terbaru dan perangkat yang mendukung.</p><p>Model 1.7B lebih ringan; model 4B/8B cenderung lebih mampu, tetapi tidak menjamin hasil selalu benar.</p></div></div><div id="ollamaConfig" class="hidden"><div class="field"><label for="ollamaBase">Alamat di komputer ini</label><input id="ollamaBase" value="http://127.0.0.1:11434"></div><div class="field"><label for="ollamaModel">Model yang sudah terpasang</label><input id="ollamaModel" value="qwen3:8b"></div><div class="model-note"><b>Gunakan model yang terpasang lokal.</b><p>Pasang Ollama, lalu jalankan <code>ollama pull qwen3:8b</code>. Untuk perangkat terbatas, gunakan model lebih kecil. Jalankan web melalui peluncur lokal bila browser menolak koneksi GitHub Pages ke komputer Anda.</p><p>Izin CORS dan jaringan lokal dijelaskan di panduan yang disertakan.</p></div></div><div id="modelStatus" class="inline-status" role="status">Pilih model, lalu aktifkan. Skripsi tidak dikirim ke layanan AI cloud.</div><div class="model-progress progress-track"><i id="modelBar"></i></div><div class="dialog-actions"><button id="disconnectAI" class="button secondary" disabled>Lepas model</button><button id="activateAI" class="button primary">${icon('spark')} Aktifkan AI lokal</button></div></dialog>
<dialog id="helpDialog" class="dialog"><div class="dialog-head"><h2>Mulai dalam empat langkah</h2><button id="closeHelp" class="icon-button" aria-label="Tutup">${icon('close')}</button></div><ol class="help-steps"><li><b>Aktifkan AI atau pilih draft sumber.</b><p>AI browser memerlukan unduhan model. Draft sumber bisa dibuat tanpa model.</p></li><li><b>Unggah skripsi dan susun artikel.</b><p>DOCX paling baik untuk tabel, gambar, dan footnote. PDF scan memakai OCR.</p></li><li><b>Review peta, isi, dan pemeriksaan.</b><p>Koreksi pemetaan bila bagian belum ditemukan. Gunakan “Sunting isi” untuk menyunting paragraf.</p></li><li><b>Unduh Word dan laporan.</b><p>Isi abstrak Inggris bisa diperiksa dan disunting. Format .doc lama perlu dikonversi ke .docx.</p></li></ol><div class="model-note">Tidak ada sistem yang dapat menjamin semua bentuk skripsi terbaca sempurna. Scan buram, simbol, format khusus, dan tabel PDF membutuhkan pemeriksaan manual.</div></dialog>
<dialog id="sourceDialog" class="dialog source-dialog"><div class="dialog-head"><h2>Jejak sumber</h2><button id="closeSource" class="icon-button" aria-label="Tutup">${icon('close')}</button></div><div id="sourceContent"></div></dialog>
<div id="toast" class="toast hidden" role="status"></div>`;
let engineKind='browser';let toastTimer;
function notify(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),5000);}
function setStatus(text,type=''){const el=$('#status');el.textContent=text;el.className='inline-status '+type;}
function setProgress(percent,text){$('#progressBar').style.width=Math.max(0,Math.min(100,percent))+'%';$('#progressLabel').textContent=text;}
function setBusy(busy){state.busy=busy;$('#progressWrap').classList.toggle('hidden',!busy);for(const el of document.querySelectorAll('.setup input,.setup select,.setup textarea,#run,#applyMapping,#chatSend,#chatInput,#referencePolicy,#editToggle,#download,#report'))el.disabled=busy;for(const el of document.querySelectorAll('.mapping-select'))el.disabled=busy||!Array.isArray(state.mapping[el.dataset.mapRole]);for(const el of document.querySelectorAll('.map-auto'))el.disabled=busy;$('#cancel').disabled=!busy;if(!busy){$('#run').disabled=!state.file;$('#applyMapping').disabled=!state.doc;$('#download').disabled=!state.plan;$('#report').disabled=!state.plan;$('#editToggle').disabled=!state.plan;}$('#activateAI').disabled=busy||ai.busy;$('#disconnectAI').disabled=busy||!ai.ready;}
function selectTab(tab){state.tab=tab;for(const el of document.querySelectorAll('[data-tab]')){const active=el.dataset.tab===tab;el.classList.toggle('active',active);el.setAttribute('aria-selected',String(active));}for(const el of document.querySelectorAll('[data-go]'))el.classList.toggle('active',el.dataset.go===tab);for(const el of document.querySelectorAll('.pane'))el.classList.toggle('active',el.id==='pane-'+tab);}
function emptyHTML(title='Setiap artikel dimulai dari sumber.'){return `<div class="empty-state"><div class="empty-illustration"><div class="empty-sheet">${icon('file')}<i></i><i></i><i></i></div><span>${icon('spark')}</span></div><span class="eyebrow small">PENELITIAN ANDA, LEBIH TERTATA.</span><h3>${esc(title)}</h3><p>Unggah skripsi, pilih cara menyusun, dan mulai.<br>Draft beserta jejak sumbernya akan muncul di sini.</p><div class="empty-steps"><span>01 Unggah</span><i></i><span>02 Susun</span><i></i><span>03 Review</span></div></div>`;}
function renderEmpty(){ $('#articleArea').innerHTML=emptyHTML();$('#mapArea').innerHTML='<div class="mini-empty">Peta sumber muncul setelah berkas dibaca.</div>';$('#qualityArea').innerHTML='<div class="mini-empty">Hasil pemeriksaan muncul setelah draft dibuat.</div>';$('#articleToolbar').classList.add('hidden');$('#articleArea').classList.remove('has-draft');$('#resultSubtitle').textContent='Dari sumber hingga draft yang siap diperiksa.';$('#draftBadge').classList.remove('ready');$('#sourceWords').textContent='—';$('#articleWords').textContent='—';$('#structureStat').innerHTML='0<span>/ 4</span>';$('#referenceStat').textContent='—';$('#issueCount').textContent='0';$('#draftBadge').textContent='BELUM ADA DRAFT';renderChat();setBusy(false);}
function useFile(file){if(!file)return;if(state.busy){notify('Tunggu proses selesai atau batalkan sebelum mengganti berkas.');return;}state.revision++;state.file=file;state.doc=state.analysis=state.plan=state.english=null;state.mapping={};state.chat=[];state.editing=false;for(const id of ['title','author','prodi','univ'])$('#'+id).value='';$('#fileName').textContent=file.name;$('#fileDetail').textContent=(file.size/1024/1024).toFixed(2)+' MB · siap dibaca';$('#dropzone').classList.add('has-file');renderEmpty();setStatus('Berkas siap. Periksa pengaturan, lalu susun artikel.');}
$('#file').onchange=e=>useFile(e.target.files[0]);$('#dropzone').addEventListener('dragover',e=>{e.preventDefault();$('#dropzone').classList.add('dragging');});$('#dropzone').addEventListener('dragleave',()=>$('#dropzone').classList.remove('dragging'));$('#dropzone').addEventListener('drop',e=>{e.preventDefault();$('#dropzone').classList.remove('dragging');useFile(e.dataTransfer.files[0]);});
for(const el of document.querySelectorAll('[data-tab],[data-go]'))el.onclick=()=>selectTab(el.dataset.tab||el.dataset.go);
for(const id of ['openAI','configureAI','aiBadge'])$('#'+id).onclick=()=>$('#aiDialog').showModal();for(const id of ['helpNav'])$('#'+id).onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=()=>$('#helpDialog').close();$('#closeAI').onclick=()=>$('#aiDialog').close();$('#closeSource').onclick=()=>$('#sourceDialog').close();
for(const el of document.querySelectorAll('[data-engine]'))el.onclick=()=>{if(ai.busy)return;engineKind=el.dataset.engine;for(const button of document.querySelectorAll('[data-engine]'))button.classList.toggle('active',button===el);$('#browserConfig').classList.toggle('hidden',engineKind!=='browser');$('#ollamaConfig').classList.toggle('hidden',engineKind!=='ollama');};
function engineStatus(){ $('#aiLabel').textContent=ai.ready?(ai.kind==='browser'?'AI browser aktif':'Ollama lokal aktif'):'AI belum aktif';$('#aiBadge').classList.toggle('ready',ai.ready);$('#configureAI').innerHTML=icon('cpu')+' '+(ai.ready?'AI aktif · ganti model':'Siapkan AI lokal');$('#outputHint').textContent=$('#outputMode').value==='source'?'Paragraf utuh dipilih dari sumber; tanpa model AI.':ai.ready?'Model aktif: '+ai.model:'Aktifkan model lewat tombol Siapkan AI.';$('#disconnectAI').disabled=!ai.ready||state.busy;$('#instructions').disabled=state.busy;}
$('#outputMode').onchange=()=>{engineStatus();$('#instructionsHint').textContent=$('#outputMode').value==='source'?'Arahan isi hanya diterapkan pada mode AI; pilihan panjang dan tabel tetap berlaku.':'Arahan isi digunakan pada mode AI lokal.';};
$('#activateAI').onclick=async()=>{if(state.busy||ai.busy)return;state.controller=new AbortController();setBusy(true);$('#activateAI').disabled=true;setProgress(0,'Menyiapkan model AI…');$('#modelStatus').textContent='Memuat model. Unduhan pertama dapat memakan waktu.';const onProgress=p=>{const percent=(p.progress||0)*100;$('#modelBar').style.width=percent+'%';$('#modelStatus').textContent=p.text||'Memuat model…';setProgress(percent,'Memuat AI lokal…');};try{if(engineKind==='browser')await ai.connectBrowser($('#browserModel').value,onProgress,state.controller.signal);else await ai.connectOllama($('#ollamaBase').value,$('#ollamaModel').value,onProgress,state.controller.signal);$('#modelStatus').textContent='AI aktif: '+ai.model;notify('AI lokal siap digunakan.');setStatus('AI lokal siap. Unggah skripsi dan susun artikel.','success');}catch(e){$('#modelStatus').textContent=e.name==='AbortError'?'Aktivasi dibatalkan.':e.message;setStatus(e.name==='AbortError'?'Aktivasi AI dibatalkan.':e.message,'warning');}finally{state.controller=null;setBusy(false);engineStatus();}};
$('#disconnectAI').onclick=async()=>{if(state.busy||ai.busy)return;await ai.disconnect();engineStatus();$('#modelStatus').textContent='Model dilepas dari memori. Cache unduhan tetap dapat digunakan.';};
$('#cancel').onclick=()=>{state.controller?.abort();ai.interrupt();$('#cancel').disabled=true;setStatus('Membatalkan proses…');};
function currentMeta(){return {title:$('#title').value,author:$('#author').value,prodi:$('#prodi').value,univ:$('#univ').value};}
function opts(){return {mode:$('#mode').value,mapping:state.mapping,includeTables:$('#includeTables').checked,includeImages:true,referencePolicy:$('#referencePolicy').value};}
function abstractData(){const section=state.plan?.sections.find(s=>s.id==='abstract');return {paragraphs:(section?.items||[]).filter(x=>x.role!=='keywords').map(x=>itemText(state.doc,x)),keywords:(section?.items||[]).filter(x=>x.role==='keywords').map(x=>itemText(state.doc,x).replace(/^kata\s*kunci\s*:?\s*/i,'')).join('; ')};}
async function run(){
 if(state.busy||!state.file)return;if($('#outputMode').value==='ai'&&!ai.ready){$('#aiDialog').showModal();notify('Aktifkan AI lokal atau pilih “Draft dari teks sumber”.');return;}
 if($('#includeEnglish').checked&&!ai.ready){$('#aiDialog').showModal();notify('Abstrak Inggris memerlukan model AI aktif.');return;}
 state.controller=new AbortController();const signal=state.controller.signal,revision=state.revision;setBusy(true);state.editing=false;state.plan=null;state.english=null;$('#articleArea').innerHTML=emptyHTML('Sedang menyusun artikel…');$('#articleToolbar').classList.add('hidden');$('#articleWords').textContent='—';$('#referenceStat').textContent='—';$('#draftBadge').textContent='MENYUSUN DRAFT';setStatus('Membaca struktur dan isi berkas…');setProgress(5,'Membaca sumber…');
 try{
  if(!state.doc||state.readOCR!==$('#ocr').checked){if(state.doc)state.mapping={};const doc=await readDocument(state.file,{ocr:$('#ocr').checked,signal,onProgress:p=>setProgress(5+p.progress*25,p.text)});checkAbort(signal);state.doc=doc;state.readOCR=$('#ocr').checked;state.analysis=analyzeThesis(doc);for(const [key,value] of Object.entries(state.analysis.meta))if($('#'+key)&&!$('#'+key).value)$('#'+key).value=value;}
  checkAbort(signal);if($('#outputMode').value==='ai'){setProgress(32,'Memetakan bagian dengan AI lokal…');await mapWithAI(ai,state.doc,state.analysis,{signal,onProgress:p=>setProgress(34,p.text)});}
  checkAbort(signal);setProgress(40,'Menyusun draft dari sumber…');let plan=generatePlan(state.doc,state.analysis,opts());state.plan=plan;render();
  if($('#outputMode').value==='ai')plan=await synthesizePlan(ai,state.doc,state.analysis,plan,{instructions:$('#instructions').value,signal,onProgress:p=>setProgress(42+p.progress*40,p.text)});
  checkAbort(signal);state.plan=plan;render();
  if($('#includeEnglish').checked){const abs=abstractData();if(!abs.paragraphs.length)state.plan.warnings.push('Abstrak Indonesia belum ditemukan; terjemahan Inggris belum dibuat.');else{try{state.english=await translateWithAI(ai,abs.paragraphs,abs.keywords,{signal,onProgress:p=>setProgress(83+p.progress*10,p.text)});}catch(e){checkAbort(signal);state.plan.warnings.push('Terjemahan Inggris gagal dan belum disertakan. '+e.message);}}}
  checkAbort(signal);if(revision!==state.revision)return;render();setProgress(96,'Menyiapkan dokumen Word…');if($('#autoDownload').checked){const blob=await exportDocx(signal);checkAbort(signal);saveBlob(blob,'Artikel_'+safeFilename(currentMeta().author.split(/\s+/)[0])+'.docx');}
  setProgress(100,'Selesai');const warnings=diagnostics(state.doc,state.analysis,state.plan).length;setStatus(`Draft selesai · ${state.plan.totalWords.toLocaleString('id-ID')} kata. ${warnings?warnings+' catatan perlu diperiksa.':'Periksa isi sebelum digunakan.'}${$('#autoDownload').checked?' Word sudah diunduh.':''}`,warnings?'warning':'success');selectTab('article');
 }catch(e){if(e.name==='AbortError'){setStatus('Proses dibatalkan. Draft yang sudah tersedia tetap dapat diperiksa.','warning');}else{console.error(e);setStatus(e.message||'Proses gagal. Periksa berkas sumber.','error');}if(state.plan)render();}
 finally{state.controller=null;setBusy(false);}
}
$('#run').onclick=run;
function tableHTML(item){return `<div class="table-scroll"><table>${item.cells.map(row=>`<tr>${row.map(c=>`<td ${c.span>1?`colspan="${c.span}"`:''}>${esc(c.text).replace(/\n/g,'<br>')}</td>`).join('')}</tr>`).join('')}</table></div>`;}
function render(){
 if(!state.plan||!state.doc||!state.analysis)return;const doc=state.doc,plan=recalc(state.plan,doc);$('#sourceWords').textContent=state.analysis.wordCount.toLocaleString('id-ID');$('#articleWords').textContent=plan.totalWords.toLocaleString('id-ID');const mapped=['intro','method','results','conclusion'].filter(id=>plan.sections.some(s=>s.id===id&&s.items.length)).length;$('#structureStat').innerHTML=mapped+'<span>/ 4</span>';$('#referenceStat').textContent=plan.sections.find(s=>s.id==='biblio')?.items.length||0;
 $('#draftBadge').textContent=plan.aiAccepted?'DRAFT AI LOKAL':'DRAFT DARI SUMBER';$('#draftBadge').classList.add('ready');$('#resultSubtitle').textContent=state.file.name;$('#articleToolbar').classList.remove('hidden');$('#draftInfo').textContent=(plan.aiAccepted?plan.aiAccepted+' potongan disusun AI':'Teks dipilih dari sumber')+' · '+plan.totalWords.toLocaleString('id-ID')+' kata';$('#editToggle').innerHTML=icon(state.editing?'check':'edit')+' '+(state.editing?'Selesai menyunting':'Sunting isi');
 const meta=currentMeta();let html=`<article class="preview-paper"><div class="paper-top"><span>RESEARCH ARTICLE</span><span>ZAIN.NET STUDIO</span></div><h1>${esc((meta.title||'JUDUL ARTIKEL').toUpperCase())}</h1><div class="paper-identity"><b>${esc(meta.author||'Nama penulis')}</b>${meta.prodi?'<span>'+esc(meta.prodi)+'</span>':''}${meta.univ?'<span>'+esc(meta.univ)+'</span>':''}</div>`;
 for(let si=0;si<plan.sections.length;si++){const sec=plan.sections[si];html+=`<section class="paper-section ${sec.id}"><h2>${esc(sec.title)}</h2>`;for(let pi=0;pi<sec.items.length;pi++){const x=sec.items[pi],src=doc.items[x.index];const text=itemText(doc,x);const ids=sourceIds(x);html+=`<div class="article-block ${x.role||'body'} ${x.ai?'ai-written':''}" data-si="${si}" data-pi="${pi}">`;if(src?.type==='table'&&x.text==null)html+=tableHTML(src);else if(state.editing)html+=`<textarea class="paragraph-editor" data-edit-si="${si}" data-edit-pi="${pi}" aria-label="Sunting paragraf ${pi+1}, ${esc(sec.title)}" rows="${Math.min(15,Math.max(3,Math.ceil(text.length/85)))}">${esc(text)}</textarea>`;else html+=`<p>${esc(text).replace(/\n/g,'<br>')}</p>`;
   if(src?.drawings?.length&&x.text==null)html+=`<div class="visual-placeholder">${icon('file')} ${src.drawings.length} gambar sumber disertakan pada Word.</div>`;if(src?.equations?.length&&x.text==null)html+='<small class="equation-note">Rumus Word dipertahankan pada file DOCX.</small>';
   if(ids.length)html+=`<button class="source-link" data-source="${ids.join(',')}">${x.ai?icon('spark'):icon('map')} ${x.ai?'AI · ':''}S${ids[0]}${ids.length>1?' +'+(ids.length-1):''}${x.edited?' · disunting':''}</button>`;html+='</div>';}
  html+='</section>';if(sec.id==='abstract'&&state.english){html+='<section class="paper-section english"><h2>ABSTRACT</h2>'+state.english.paragraphs.map((p,i)=>state.editing?`<textarea class="paragraph-editor" data-english="${i}" rows="${Math.max(3,Math.ceil(p.length/85))}">${esc(p)}</textarea>`:`<p>${esc(p)}</p>`).join('')+`<p class="keywords">Keywords: ${state.editing?`<input id="englishKeywords" value="${esc(state.english.keywords)}" aria-label="Keywords">`:esc(state.english.keywords)}</p></section>`;}}
 html+='<div class="paper-bottom">Draft artikel · periksa kembali sebelum publikasi</div></article>';
 $('#articleArea').innerHTML=html;$('#articleArea').classList.add('has-draft');renderMapping();renderQuality();renderChat();bindSourceLinks();$('#download').disabled=state.busy;$('#report').disabled=state.busy;
}
function renderMapping(){if(!state.analysis)return;let html='';for(const role of ['abstract','intro','method','results','discussion','conclusion']){const chosen=Array.isArray(state.mapping[role])?state.mapping[role]:null;const auto=state.analysis.roleBlocks[role]||[];html+=`<details class="mapping-card"><summary><span>${esc(ROLES[role])}</span><span class="mapping-label">${chosen?'Manual':auto.length?auto.length+' blok':'Belum ditemukan'}</span></summary><div class="mapping-content"><label class="mapping-auto"><input type="checkbox" class="map-auto" data-role="${role}" ${chosen?'':'checked'} ${state.busy?'disabled':''}> Deteksi otomatis</label><select class="mapping-select" data-map-role="${role}" multiple size="5" aria-label="Pilih sumber ${esc(ROLES[role])}" ${!chosen||state.busy?'disabled':''}>${state.analysis.blocks.map(b=>`<option value="${b.id}" ${(chosen||auto.map(x=>x.id)).includes(b.id)?'selected':''}>${esc(b.label)} · ${b.wordCount} kata</option>`).join('')}</select><small>Ctrl/⌘ + klik untuk memilih lebih dari satu blok.</small><div class="mapping-sources">${(chosen?chosen.map(id=>state.analysis.blocks.find(b=>b.id===id)).filter(Boolean):auto).map(b=>`<div><span class="confidence-dot ${b.confidence<.65?'uncertain':''}"></span><span>${esc(b.label)}<small>${b.wordCount} kata · ${b.aiMapped?'Pemetaan AI':'Deteksi sumber'}${b.confidence<.65?' · perlu review':''}</small></span><button class="icon-button" data-source="${Array.from({length:Math.min(b.end-b.textStart,6)},(_,i)=>b.textStart+i).join(',')}" aria-label="Lihat sumber">${icon('file')}</button></div>`).join('')||'<small>Isi tidak dibuat jika belum ada sumber yang terpetakan.</small>'}</div></div></details>`;}
 html+='<details class="source-inventory"><summary>Semua blok sumber · '+state.analysis.blocks.length+'</summary>'+state.analysis.blocks.map(b=>`<div><b>${esc(b.label)}</b><span>${esc(ROLES[b.role])} · ${b.wordCount} kata</span></div>`).join('')+'</details>';$('#mapArea').innerHTML=html;
 for(const el of document.querySelectorAll('.map-auto'))el.onchange=()=>{const role=el.dataset.role;if(el.checked)delete state.mapping[role];else state.mapping[role]=(state.analysis.roleBlocks[role]||[]).map(x=>x.id);renderMapping();bindSourceLinks();};
 for(const el of document.querySelectorAll('.mapping-select'))el.onchange=()=>{state.mapping[el.dataset.mapRole]=[...el.selectedOptions].map(x=>x.value);};
}
$('#applyMapping').onclick=run;
function renderQuality(){const notes=diagnostics(state.doc,state.analysis,state.plan);$('#issueCount').textContent=notes.length;const generated=state.plan.sections.flatMap(s=>s.items).filter(x=>x.ai).length;let html=`<div class="quality-overview"><div class="quality-emblem">${icon('check')}</div><div><b>${notes.length?notes.length+' catatan untuk diperiksa':'Bagian utama tersedia'}</b><p>${generated?generated+' paragraf disusun AI dan memiliki penanda sumber.':'Draft menggunakan paragraf dari dokumen sumber.'}</p></div></div>`;html+=notes.map(n=>`<div class="quality-note">${icon('help')}<span>${esc(n)}</span></div>`).join('');html+=`<div class="quality-facts"><div><span>Footnote terpakai</span><b>${sourceFootnotes(state.doc,state.plan).length}</b></div><div><span>Tabel disertakan</span><b>${state.plan.sections.flatMap(s=>s.items).filter(x=>state.doc.items[x.index]?.type==='table').length}</b></div><div><span>Model ringkasan</span><b>${esc(state.plan.aiModel||'Tanpa model')}</b></div><div><span>Referensi</span><b>${state.plan.referencePolicy==='all'?'Semua sumber':'Sitasi cocok'}</b></div></div>`;if(state.plan.validation?.length)html+='<details class="validation-details"><summary>Hasil pemeriksaan per potongan · '+state.plan.validation.length+'</summary>'+state.plan.validation.map(v=>`<div class="validation-item"><span class="validation-badge ${v.status}">${v.status==='fallback'?'SUMBER ASLI':'REVIEW MAKNA'}</span><b>${esc(ROLES[v.section])}</b><p>${esc(v.message)}</p><button class="source-link" data-source="${v.sourceIds.join(',')}">Lihat sumber ${v.sourceIds.map(i=>'S'+i).join(', ')}</button></div>`).join('')+'</details>';$('#qualityArea').innerHTML=html;}
function bindSourceLinks(){for(const button of document.querySelectorAll('[data-source]'))button.onclick=()=>showSources(button.dataset.source.split(',').filter(Boolean).map(Number));}
function showSources(ids){if(!state.doc)return;$('#sourceContent').innerHTML=ids.map(id=>{const src=state.doc.items[id];return src?`<div class="source-detail"><div><b>S${id}</b><span>${src.page?'Halaman '+src.page:'Blok dokumen '+(id+1)}${src.ocr?' · OCR':''}</span></div>${src.type==='table'?tableHTML(src):'<p>'+esc(src.text)+'</p>'}${src.footnoteIds?.length?'<small>Footnote: '+esc(src.footnoteIds.map(n=>state.doc.footnotes.get(n)||n).join(' | '))+'</small>':''}</div>`:'';}).join('');$('#sourceDialog').showModal();}
$('#editToggle').onclick=()=>{if(state.busy)return;state.editing=!state.editing;render();};
$('#articleArea').addEventListener('input',e=>{const target=e.target;if(target.matches('[data-edit-si]')){const sec=state.plan.sections[+target.dataset.editSi],item=sec.items[+target.dataset.editPi];item.text=target.value;item.edited=true;item.needsReview=true;if(sec.id==='abstract'){state.english=null;if($('#includeEnglish').checked)notify('Abstrak diubah. Terjemahkan kembali dengan menyusun ulang, atau isi Inggris setelah terjemahan.');}recalc(state.plan,state.doc);$('#articleWords').textContent=state.plan.totalWords.toLocaleString('id-ID');renderQuality();bindSourceLinks();}else if(target.matches('[data-english]')&&state.english){state.english.paragraphs[+target.dataset.english]=target.value;state.english.body=state.english.paragraphs.join('\n\n');state.english.edited=true;}else if(target.id==='englishKeywords'&&state.english)state.english.keywords=target.value;});
for(const id of ['title','author','prodi','univ'])$('#'+id).addEventListener('input',()=>{if(state.plan&&!state.editing)render();});
$('#referencePolicy').onchange=()=>{if(state.plan){syncReferences(state.doc,state.analysis,state.plan,$('#referencePolicy').value);render();}};
$('#includeEnglish').onchange=()=>{if(!$('#includeEnglish').checked){state.english=null;if(state.plan)render();}else if(state.plan)notify('Susun ulang artikel untuk membuat abstrak Inggris.');};
function renderChat(){let html='';if(!state.chat.length)html=`<div class="chat-empty">${icon('chat')}<p>Model AI membaca potongan sumber yang relevan dengan pertanyaan Anda.</p></div>`;else for(const message of state.chat){html+=`<div class="chat-message ${message.role}"><span class="chat-author">${message.role==='user'?'ANDA':'ZAIN AI · LOKAL'}</span><p>${esc(message.text).replace(/\n/g,'<br>')}</p>${message.sources?.length?'<div class="chat-source-list">'+message.sources.map(s=>`<button data-source="${s.sourceId}">S${s.sourceId}${s.page?' · hlm. '+s.page:''}</button>`).join('')+'</div>':''}</div>`;}$('#chatLog').innerHTML=html;bindSourceLinks();}
$('#chatForm').onsubmit=async e=>{e.preventDefault();if(state.busy)return;const question=norm($('#chatInput').value);if(!question)return;if(!state.doc){notify('Baca skripsi dahulu dengan tombol Susun artikel.');return;}if(!ai.ready){$('#aiDialog').showModal();return;}state.chat.push({role:'user',text:question});$('#chatInput').value='';renderChat();state.controller=new AbortController();setBusy(true);setProgress(50,'AI mencari jawaban dari sumber…');try{const reply=await chatWithDocument(ai,state.doc,question,{signal:state.controller.signal});state.chat.push({role:'assistant',...reply});}catch(err){state.chat.push({role:'assistant',text:err.name==='AbortError'?'Pertanyaan dibatalkan.':err.message});}finally{state.controller=null;setBusy(false);renderChat();$('#chatLog').scrollTop=$('#chatLog').scrollHeight;}};
for(const el of document.querySelectorAll('[data-question]'))el.onclick=()=>{$('#chatInput').value=el.dataset.question;$('#chatInput').focus();};
function saveBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove();},1500);}
async function exportDocx(signal){return buildArticleDocx(state.doc,state.analysis,state.plan,currentMeta(),{signal,englishAbstract:$('#includeEnglish').checked?state.english:null,format:{fontSize:+$('#fontSize').value,lineSpacing:+$('#lineSpacing').value,marginCm:3}});}
$('#download').onclick=async()=>{if(state.busy||!state.plan)return;state.controller=new AbortController();setBusy(true);setProgress(80,'Menyiapkan Word…');try{const blob=await exportDocx(state.controller.signal);checkAbort(state.controller.signal);saveBlob(blob,'Artikel_'+safeFilename(currentMeta().author.split(/\s+/)[0])+'.docx');setStatus('Dokumen Word berhasil diunduh.','success');}catch(e){setStatus(e.message,'error');}finally{state.controller=null;setBusy(false);}};
$('#report').onclick=()=>{if(!state.plan)return;const meta=currentMeta();const sections=state.plan.sections.map(s=>`- ${s.title}: ${s.items.length} blok, ${s.items.reduce((n,x)=>n+wc(itemText(state.doc,x)),0)} kata`).join('\n');const notes=diagnostics(state.doc,state.analysis,state.plan);const validation=(state.plan.validation||[]).map(v=>`- ${ROLES[v.section]} (${v.sourceIds.map(i=>'S'+i).join(', ')}): ${v.status} — ${v.message}`).join('\n');const report=`ZAIN.NET ARTICLE STUDIO V${VERSION}\n\nFile sumber: ${state.file.name}\nJudul: ${meta.title}\nPenulis: ${meta.author}\nProgram studi: ${meta.prodi}\nUniversitas: ${meta.univ}\nFormat sumber: ${state.doc.format}\nKata sumber: ${state.analysis.wordCount}\nKata artikel: ${state.plan.totalWords}\nModel: ${state.plan.aiModel||'Tanpa model; teks sumber'}\nPotongan AI digunakan: ${state.plan.aiAccepted||0}\nPotongan kembali ke sumber: ${state.plan.aiRejected||0}\nAbstrak Inggris: ${state.english?'Tersedia; '+state.english.paragraphs.length+' paragraf':'Belum disertakan'}\nFootnote terpakai: ${sourceFootnotes(state.doc,state.plan).length}\n\nBAGIAN ARTIKEL\n${sections}\n\nCATATAN PEMERIKSAAN\n${notes.map(n=>'- '+n).join('\n')||'- Periksa kembali isi sebelum publikasi.'}\n\nVALIDASI AI\n${validation||'Mode sumber; tidak ada ringkasan AI.'}\n\nJEJAK SUMBER\n${state.plan.sections.flatMap(s=>s.items.map(x=>s.title+': '+sourceIds(x).map(i=>'S'+i).join(', ')+(x.edited?' — disunting manual':''))).join('\n')}\n\nPenanda dan angka bukan jaminan kebenaran semantik. Periksa makna, rujukan, OCR, dan format jurnal sebelum digunakan.\n`;saveBlob(new Blob([report],{type:'text/plain;charset=utf-8'}),'Laporan_Artikel_ZAINNET.txt');};
// Cache only the application shell, never thesis files or local AI requests.
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(location.protocol==='file:')setStatus('Buka melalui GitHub Pages atau peluncur lokal; ES modules tidak dapat berjalan dengan klik file biasa.','warning');
renderEmpty();engineStatus();
