import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeThesis,generatePlan,applyAIMapping} from '../article-ai.js';
import {validateParagraph,synthesizePlan,LocalAI} from '../local-ai.js';
import {numericTokens,parseJSON,itemText} from '../utils.js';
const paragraph='Penelitian ini menggunakan pendekatan kuantitatif dengan sampel 30 responden. Data dikumpulkan melalui kuesioner dan dianalisis menggunakan regresi linear. Nilai signifikansi yang diperoleh sebesar 0,032. Hasil penelitian harus dipahami dalam konteks sumber data yang tersedia di lokasi penelitian.';
function document(texts){return {items:texts.map((text,index)=>({index,text,type:'p',style:'',footnoteIds:[],boldRatio:text===text.toUpperCase()?1:0,isToc:false})),footnotes:new Map(),warnings:[]};}
function standard(){return document(['BAB I PENDAHULUAN',paragraph,'BAB II METODE PENELITIAN',paragraph,'BAB III HASIL PENELITIAN',paragraph,'BAB IV PENUTUP',paragraph,'DAFTAR PUSTAKA','Sugiyono. (2020). Metode Penelitian Kuantitatif. Bandung: Alfabeta.','LAMPIRAN','RAHASIA']);}
test('Judul BAB mengalahkan asumsi nomor',()=>{const d=standard(),a=analyzeThesis(d);assert.equal(a.roleBlocks.method[0].start,2);assert.equal(a.roleBlocks.results[0].start,4);assert.equal(a.roleBlocks.conclusion[0].start,6);});
test('Judul bernomor tanpa BAB dibaca semantik',()=>{const d=document(['1. PENDAHULUAN',paragraph,'2. METODE PENELITIAN',paragraph,'3. HASIL DAN PEMBAHASAN',paragraph,'4. KESIMPULAN',paragraph]);const p=generatePlan(d,analyzeThesis(d));assert.deepEqual(p.sections.map(s=>s.id),['intro','method','results','conclusion']);});
test('Tidak mengambil daftar isi dan lampiran',()=>{const d=standard();d.items.unshift({text:'BAB III HASIL PENELITIAN ........ 10',type:'p',isToc:true});d.items.forEach((x,i)=>x.index=i);const a=analyzeThesis(d),p=generatePlan(d,a);assert(!p.sections.some(s=>s.items.some(x=>itemText(d,x).includes('RAHASIA'))));assert.equal(a.roleBlocks.results[0].start,5);});
test('Menyediakan pemetaan manual beberapa blok dan penghilangan eksplisit',()=>{const d=standard(),a=analyzeThesis(d);const p=generatePlan(d,a,{mapping:{intro:[],method:[a.roleBlocks.method[0].id]}});assert(!p.sections.some(s=>s.id==='intro'));assert(p.sections.some(s=>s.id==='method'));});
test('AI tidak menimpa judul yang jelas',()=>{const d=standard(),a=analyzeThesis(d),b=a.roleBlocks.method[0];applyAIMapping(a,[{blockId:b.id,role:'results',confidence:.99}]);assert.equal(b.role,'method');});
test('Tidak membuat referensi dari sumber yang tidak disitasi',()=>{const d=standard();const p=generatePlan(d,analyzeThesis(d));assert(!p.sections.some(s=>s.id==='biblio'));const all=generatePlan(d,analyzeThesis(d),{referencePolicy:'all'});assert.equal(all.sections.find(s=>s.id==='biblio').items.length,1);});
test('Angka baru dan sumber palsu ditolak',()=>{const d=document([paragraph]);assert.equal(validateParagraph({text:paragraph.replace('30','50'),sourceIds:[0]},new Set([0]),d).ok,false);assert.equal(validateParagraph({text:paragraph,sourceIds:[9]},new Set([0]),d).ok,false);assert.equal(validateParagraph({text:paragraph,sourceIds:[0]},new Set([0]),d).ok,true);});
test('Arah signifikansi negatif tidak boleh berubah',()=>{const text='Hasil penelitian menunjukkan bahwa variabel ini tidak signifikan terhadap kepuasan responden di lokasi penelitian.';const d=document([text]);assert.equal(validateParagraph({text:text.replace('tidak signifikan','signifikan'),sourceIds:[0]},new Set([0]),d).ok,false);});
test('Desimal, persen, dan tahun tidak diubah oleh normalisasi',()=>{assert.deepEqual(numericTokens('0,032; 30 responden; 80%; (2020).'),['0,032','30','80%','2020']);});
test('JSON berpagar diterima; jawaban rusak ditolak',()=>{assert.deepEqual(parseJSON('```json\n{"a":1}\n```'),{a:1});assert.throws(()=>parseJSON('bukan JSON'));});
test('Ringkasan yang gagal pemeriksaan kembali ke teks sumber',async()=>{const d=standard(),a=analyzeThesis(d),p=generatePlan(d,a);const fake={model:'TEST-STUB',complete:async()=>JSON.stringify({paragraphs:[{text:paragraph.replace('30','999'),sourceIds:[1]}]})};const result=await synthesizePlan(fake,d,a,p);assert.equal(result.aiAccepted,0);assert(result.aiRejected>0);assert(result.sections.every(s=>s.items.every(x=>!x.ai)));assert(result.sections[0].items.some(x=>itemText(d,x).includes('30')));});
test('Ringkasan valid mempunyai penanda sumber',async()=>{const d=standard(),a=analyzeThesis(d),p=generatePlan(d,a);const fake={model:'TEST-STUB',complete:async messages=>{const payload=JSON.parse(messages[1].content.split('DATA:\n')[1]);return JSON.stringify({paragraphs:payload.map(x=>({text:x.text,sourceIds:x.sourceIds}))});}};const result=await synthesizePlan(fake,d,a,p);assert(result.aiAccepted>0);assert(result.sections[0].items[0].sourceIds.length);assert(result.sections[0].items[0].needsReview);});
test('Proses batal tidak diteruskan sebagai keberhasilan',async()=>{const d=standard(),a=analyzeThesis(d),p=generatePlan(d,a),ctrl=new AbortController();ctrl.abort();await assert.rejects(()=>synthesizePlan({model:'TEST',complete:async()=>''},d,a,p,{signal:ctrl.signal}),{name:'AbortError'});});
test('Ollama hanya menerima endpoint komputer sendiri',async()=>{const ai=new LocalAI();await assert.rejects(()=>ai.connectOllama('https://example.com','qwen3:8b'),/komputer ini/);assert.equal(ai.ready,false);});
test('Transport Ollama mengirim konfigurasi JSON dan mode lokal',async()=>{const original=globalThis.fetch;const requests=[];globalThis.fetch=async(url,options={})=>{requests.push({url,options});return {ok:true,json:async()=>url.endsWith('/tags')?{models:[{name:'qwen3:8b'}]}:{message:{content:'{"paragraphs":[]}'},done_reason:'stop'}};};try{const ai=new LocalAI();await ai.connectOllama('http://127.0.0.1:11434','qwen3:8b');const result=await ai.complete([{role:'user',content:'DATA UJI'}],{json:true});assert.equal(result,'{"paragraphs":[]}');const body=JSON.parse(requests[1].options.body);assert.equal(body.stream,false);assert.equal(body.think,false);assert.equal(body.format,'json');assert.equal(body.model,'qwen3:8b');assert.equal(body.options.seed,42);assert(requests.every(r=>r.url.startsWith('http://127.0.0.1:11434/')));}finally{globalThis.fetch=original;}});
test('Paragraf sangat panjang tetap utuh bila melebihi konteks',async()=>{const long=paragraph.repeat(15),d=document(['PENDAHULUAN',long]),a=analyzeThesis(d),p=generatePlan(d,a);const ai={model:'TEST-STUB',complete:async()=>{throw new Error('Tidak boleh memotong sumber ini');}};const result=await synthesizePlan(ai,d,a,p);assert(result.aiRejected);assert(result.sections[0].items.some(x=>itemText(d,x)===long));});
